# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

infer_mi_network <- function(df) {
    .Call('_NetworkInferenceR_infer_mi_network', PACKAGE = 'NetworkInferenceR', df)
}

infer_puc_network <- function(df) {
    .Call('_NetworkInferenceR_infer_puc_network', PACKAGE = 'NetworkInferenceR', df)
}

infer_pid_network <- function(df) {
    .Call('_NetworkInferenceR_infer_pid_network', PACKAGE = 'NetworkInferenceR', df)
}

